### ISSUE TITLE
Some RSS Feed make app crash

### ISSUE THREAD

**Issue by onigetoc** [jackysee/RssJson#2]
Some RSS Feed make app crash

http://wearechange.org/feed/
or
http://www.androidpolice.com/feed/

If i make a call from ajax, the app crash and i have to deploy again

`Uncaught TypeError: Cannot read property 'url' of undefined`

**Comment by onigetoc** [comment]
Is the person who did this script is dead???
Never get answer

**Comment by jackysee** [comment]
Hi, it seems that feedburner is not responding with HTML rather than RSS when the header has browser string in it. It's now removed.
