### ISSUE TITLE
Adding content:encoded (description)

### ISSUE THREAD

**Issue by onigetoc** [jackysee/RssJson#4]
Hi, 
suggestion: I added content:encoded if i need it.

https://github.com/onigetoc/RssJson/blob/master/rss.js#L83

**Comment by jackysee** [comment]
I'm all good with this, you can send a pull request

**Comment by onigetoc** [comment]
question, Why removing the user agent?
Some rss files will stop working without user agent.
ex: http://stopmensonges.com/feed
If i put back user agent, it will work again

**Comment by jackysee** [comment]
So the user agent cannot be a browser string.
I've updated to have a simple string in the user agent then.

**Comment by jackysee** [comment]
Code updated. The pull request is ignored as it contains too many un-related file. I've updated only the relevant part.
